### ISSUE TITLE
Fonts display strangely in Firefox, but not Chromium.

### ISSUE THREAD

**Issue by blaseur** [cupslab/password_meter#2]
Fonts display strangely in Firefox, but not Chromium. This results in the "show password & detailed feedback" line from overflowing into the next line.
![screenshot from 2017-05-07 22 31 03](https://cloud.githubusercontent.com/assets/1356405/25788614/7801c59a-3378-11e7-970b-4870af06f438.png)

**Comment by m33x** [comment]
Same issue, please see [this](https://github.com/cupslab/password_meter/issues/3#issuecomment-299909635).
