### ISSUE TITLE
Continue button doesn't line up correctly in Firefox

### ISSUE THREAD

**Issue by blaseur** [cupslab/password_meter#3]
In Firefox, the Continue button is not right-aligned with the other fields.

Spacing is fine in Chromium.

![screenshot from 2017-05-07 22 31 03](https://cloud.githubusercontent.com/assets/1356405/25788644/a3118bda-3378-11e7-982c-87b55da3b837.png)

**Comment by m33x** [comment]
[config.css](https://github.com/cupslab/password_meter/blob/master/example/config.css) may cause the issue. Please have a look at 
`body {
  font-family: sans-serif;`
 
If disabled, it does no longer overflow in Firefox & Chrome (Ubuntu 16.04).
![selection_012](https://cloud.githubusercontent.com/assets/883685/25812756/8f562e1c-3417-11e7-910c-2cc9f61e2d55.jpg)

A possible workaround could be using [Web typography](https://fonts.google.com/specimen/Open+Sans).

**Comment by blaseur** [comment]
Thanks, m33x! Fixed in latest commit by removing that line.
