### ISSUE TITLE
html in form's fields is not escaped

### ISSUE THREAD

**Issue by p4tpr0** [cupslab/password_meter#6]
Step to reproduce:
- choose a username with html tag in it, for example: `be<h1>good`
- check "Show Password & Detailed Feedback"
- type a password that includes the username, for example: `can't be<h1>good`

result: html tag in not escaped in the feedback window.

**Comment by lujobauer** [comment]
This definitely seems like something to fix. :-)

Michael and Blase, can one of you do this?

-Lujo

patpro wrote:

**Comment by lujobauer** [comment]
I'll do it this week

________________________________________

**Comment by stroucki** [comment]
There's also some confusion with the other checks like "Make your password longer than 0 characters". This is a separate issue.

**Comment by stroucki** [comment]
pull request #9

**Comment by blaseur** [comment]
Fixed in commit 5e11512. Thanks, stroucki.
